#!/bin/bash

sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width        3
bspc config window_gap          30

bspc config normal_border_color     "#BFC1B1"
bspc config active_border_color     "#718173"
bspc config focused_border_color    "#718173"


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config focus_follows_pointer	true
bspc config pointer_modifier	super


#bspc rule -a audasiuos desktop='^3' state=floating follow=on
#bspc rule -a firefox desktop='^2'
#bspc rule -a  state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


# For Monitor
xrandr --output HDMI-0 --mode 1920x1080 --rate 100 &


# Pulseaudio
pulseaudio --start &


# Layout
setxkbmap -layout us,ru -option grp:alt_shift_toggle


# Picom
picom --backend glx &


# Cursor
xsetroot -cursor_name left_ptr &


# Wallpaper
feh --bg-scale /wallpaper/'forest.jpg' &


# status bar (dzen2)
while true; do date; done | dzen2 -bg '#808D79' -fg '#D9D7CA' -fn 'NotoSans' -e -u -p &
