#!/bin/bash

sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width        10
bspc config window_gap          30

bspc config normal_border_color     "#7c3687"
bspc config active_border_color     "#28002b"
bspc config focused_border_color    "#7c0587"


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config focus_follows_pointer	true
bspc config pointer_modifier	super


#bspc rule -a audasiuos desktop='^3' state=floating follow=on
#bspc rule -a firefox desktop='^2'
#bspc rule -a  state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


# For Monitor
xrandr --output HDMI-0 --mode 1920x1080 --rate 100 &


# Pulseaudio
pulseaudio --start &


# Layout
setxkbmap -layout us,ru -option grp:alt_shift_toggle


# Picom
picom --backend xrender &


# Cursor
xsetroot -cursor_name left_ptr &


# Wallpaper
feh --bg-scale /wallpaper/1.jpg &
