#!/usr/bin/env bash

sxhkd &

bspc monitor -d I II III IV

bspc config border_width        10
bspc config window_gap          30

bspc config normal_border_color     "#C1A3BE"
bspc config active_border_color     "#AC44A2"
bspc config focused_border_color    "#C074B8"



bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a audasiuos desktop='^3' state=floating follow=on
#bspc rule -a firefox desktop='^2'
#bspc rule -a  state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


# For Monitor
xrandr --output HDMI-0 --mode 1920x1080 --rate 100 &


# Wallpaper
feh --bg-scale .../path/... &
